//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Read_Write_Slowly
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenre
    {
        public int BookGenreId { get; set; }
        public int BookId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
