//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Read_Write_Slowly
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleApplication
    {
        public int RoleApplicationId { get; set; }
        public int UserId { get; set; }
        public int RequestedRoleId { get; set; }
        public string Status { get; set; }
        public string CreatedAt { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}
